FROM        python:3.7.0-slim
MAINTAINER  yeojin.dev@gmail.com

ENV         PROJECT_DIR             /srv/

RUN         apt -y update && apt -y dist-upgrade
RUN         apt -y install build-essential

WORKDIR     ${PROJECT_DIR}
COPY        ./app_blue              ${PROJECT_DIR}

RUN         pip install --upgrade pip
RUN         pip install django

EXPOSE      7001

CMD         ./manage.py runserver 0:7001
